/**
 * @file language resources
 * @author atom-yang
 */

export const resources = {
  en: {
    translation: {
      confirm: 'confirm',
      name: 'name',
      register: 'REG',
      nickName: 'nick name',
      nickNamePlaceholder: '2-15 Chinese or English Characters',
      password: 'PWD',
      passwordPlaceholder: 'password placeholder',
      confirmPassword: 'con firm',
      confirmPasswordPlaceholder: '',
      nickNameNotValid: 'name is not valid',
      passwordNotValid: 'password is not valid',
      confirmPasswordNotValid: 'confirmed password is not valid',
      inValidTitle: 'Notification',
      inValidRegister: 'register failed, please try later',
      registerSuccessTitle: 'successfully',
      registerSuccessInfoFir: 'Welcome to use AElf',
      registerSuccessInfoSec: 'You are the',
      registerSuccessInfoThird: 'access user',
      address: 'address',
      addressAbbreviation: 'ADD',
      registerSuccessInfo: '欢迎使用AElf不删档测试网络！\n您是第{{count}}位接入用户。\n地址：{{address}}',
      allRecords: 'All Records',
      myRecords: 'My Records',
      rankTips: 'Betting no less than 3 times, you can participate in the ranking',
      batAmount: 'Bat Amount',
      player: 'player',
      balance: 'balance',
      bets: 'bets',
      time: 'time',
      done: 'Done',
      backupMnemonic: 'Backup mnemonic',
      mnemonicPrompt: 'Mnemonics are used to restore identity and password, please keep it safe',
      startGame: 'Start',
      login: 'login',
      accountBalance: 'Current account balance',
      resultConfirm: 'OK',
      playTips: 'Betting no less than 3 times, you can participate in the ranking',
      result: 'result',
      backupQRcode: 'Backup QR code',
      qrcodePrompt: 'QR code is used to restore identity and password, please keep it safe',
      inputTips: 'Please enter the amount in the correct format',
      excessQuantity: 'You don\'t have so many cards',
      exportQRcode: 'Export QR code',
      game: 'Game',
      pullRefresh: 'Pull down can refresh',
      refreshImmediately: 'Release and refresh immediately',
      completeRefresh: 'Complete refresh'
    }
  },
  zh: {
    translation: {
      confirm: '确认',
      name: '姓名',
      register: '注册',
      nickName: '昵称',
      nickNamePlaceholder: '2-15个中英文，数字字符',
      password: '密码',
      passwordPlaceholder: '6-16位字母、数字或者符号',
      confirmPassword: '重复密码',
      confirmPasswordPlaceholder: '',
      nickNameNotValid: '昵称输入非法',
      passwordNotValid: '密码输入非法',
      confirmPasswordNotValid: '重复密码输入非法',
      inValidTitle: '提示',
      inValidRegister: '注册失败，请稍后重试',
      registerSuccessTitle: '注册成功',
      registerSuccessInfoFir: '欢迎使用AElf不删档测试网络',
      registerSuccessInfoSec: '您是第',
      registerSuccessInfoThird: '位接入用户',
      address: '地址',
      addressAbbreviation: '地址',
      registerSuccessInfo: '欢迎使用AElf不删档测试网络！\n您是第{{count}}位接入用户。\n地址：{{address}}',
      allRecords: '所有记录',
      myRecords: '我的记录',
      rankTips: '投注次数不少于3次,即可参与排名',
      batAmount: '下注金额',
      player: '玩家',
      balance: '余额',
      bets: '投注次数',
      time: '时间',
      done: '完成',
      backupMnemonic: '备份助记词',
      mnemonicPrompt: '助记词用于恢复身份和密码,请妥善保管',
      startGame: '开始游戏',
      login: '登录',
      accountBalance: '当前账户余额',
      resultConfirm: '确认',
      playTips: '投注次数不少于3次，即可参与排名',
      result: '结果',
      backupQRcode: '备份二维码',
      qrcodePrompt: '二维码用于恢复身份,请妥善保管',
      inputTips: '请输入正确格式的数字',
      excessQuantity: '你没有这么多的Card',
      exportQRcode: '导出二维码',
      game: '游戏',
      pullRefresh: '下拉可以刷新',
      refreshImmediately: '松开立即刷新',
      completeRefresh: '完成刷新',
      scanRegister: '未在本地检测到您的地址信息，若您已申请过游戏账号，可点击此处扫码恢复账号信息！'
    }
  }
};
